plot_shapes = False         # generate the two left figures in Fig. 3
generate_table_opt = False      # generate Table 1
run_forward_opt = False     # output needed for the next two options
generate_dp = False        # generate the right plot of Fig. 3
generate_mp4 = False        # generate mp4 of the time dependent results


import visualization.colormaps 

# plot shapes
from visualization.visualize_shapes import visualize_shape

if plot_shapes:
    fnames = ["mesh_triangles.xdmf", "domains_final.xdmf"] # these files are in folder /example/FSI/mesh
    outname = ["init_plot.png", "final_plot.png"]
    for i in range(len(fnames)):
        print('visualize ', fnames[i])
        visualize_shape(fnames[i], outname[i])

# generate latex table
from visualization.read_terminal_output import generate_table
if generate_table_opt:
    txtname = "terminal_2207.txt"   # terminal output of simulation needs to be saved to /example/FSI/mesh/Output/txtname
    txtout = 'table.txt'
    txtout_all = 'to_shortened.txt'
    generate_table(txtname, txtout, txtout_all)

# run forward simulation on initial and optimized geometry
from visualization.run_forward_solve import run_forward

only_optimized = True # set to False if initial domain was not optimized
only_initial = False
if only_optimized:
    initial = [False]
elif only_initial:
    initial = [True]
else:
    initial = [True, False]

if False in initial:
    import sys, os
    from pathlib import Path
    here = Path(__file__).parent.resolve()
    folder = str(here) + "/mesh"
    os.chdir(folder)
    os.system("cp domains_final.h5 domains_new.h5 && cp domains_final.xdmf domains_new.xdmf")
    os.system("cp facet_mesh_final.h5 facet_mesh_new.h5 && cp facet_mesh_final.xdmf facet_mesh_new.xdmf")
    os.system("cp mesh_triangles_final.h5 mesh_triangles_new.h5 && cp mesh_triangles_final.xdmf mesh_triangles_new.xdmf")

if run_forward_opt: 
    T = 30.0 #time horizon 
    deltat = 0.005 # needed, otherwise numerical issues for large time horizons
    for i in initial:
        run_forward(i, T, deltat)


# generate displacement plot
from visualization.plot_displacement import plot_displacement, colors
import numpy as np
from pathlib import Path
here = Path(__file__).parent.parent.resolve()

foldernames = ["Init", "Opt"]  # folders in /example/FSI/Output/Forward generated by run_forward

if generate_dp:
    names=  ["initial geometry", "optimized geometry"] 

    times_list = []
    displacement_list = []

    for i in foldernames:
        str_ = str(here) + "/FSI/Output/Forward/" + i
        times_list.append(np.loadtxt(str_ + "/times.txt"))
        displacement_list.append(np.loadtxt(str_ + "/displacementy.txt"))

    plot_displacement(displacement_list, times_list,
                        str(here)+"/FSI/Output/displacement_plot.pdf", colors, names)

# generate clips
from visualization.visualize_simulation import make_movie

only_init = False
only_opt = False
gifnames = ["init_fsi.gif", "opt_fsi.gif"]
if only_init: 
    f_names = [foldernames[0]]
    g_names = [gifnames[0]]
elif only_opt:
    f_names = [foldernames[1]]
    g_names = [gifnames[1]]
else:
    f_names = foldernames
    g_names = gifnames

if generate_mp4:   
    for i in range(len(f_names)):
        make_movie(foldername=f_names[i], gifname=g_names[i])