plot_shapes = False         # generate the two left figures in Fig. 3
generate_table_opt = False     # generate Table 1
run_forward_opt = True     # output needed for the next two options
rerun_simulation = False
generate_dp = True       # generate the right plot of Fig. 3
generate_mp4 = False        # generate mp4 of the time dependent results

import sys, os
from pathlib import Path
here = Path(__file__).parent.resolve()

import visualization.colormaps 

# plot shapes
from visualization.visualize_shapes import visualize_shape

print('__Set options__')
option = 2 # 0: optimization of obstacle, 1: optimzation of interface, 2: extra example 1
if option == 0:
    path_mesh = str(here) + "/" + "mesh"
    if plot_shapes:
        fnames = ["mesh/mesh_triangles.xdmf", "mesh/domains_final.xdmf"] # these files are in folder /example/FSI/
        outname = ["mesh/init_plot.png", "mesh/final_plot.png"]
    if generate_table_opt:
        txtname = "terminal_jun3_.txt"   # terminal output of simulation needs to be saved to /example/FSI/txtname
        txtout = 'mesh/table.txt'
        txtout_all = 'mesh/to_shortened.txt'
    if generate_dp:
        foldernames = ["Init", "Opt"]  # folders in /example/FSI/Output/Forward generated by run_forward
        points = [[0.6, 0.2], [0.6, 0.2]]
    if generate_mp4:
        gifnames = ["init_fsi.gif", "opt_fsi.gif"]
    T = 30.0 #time horizon 
    deltat = 0.005 #needed, otherwise numerical issues for large time horizons
    drag = True
    factor = 1
    xrange = [0, 30]
    yrange = [-0.1, 0.1]
    move_dp = True

elif option == 1:
    path_mesh = str(here) + "/" + "mesh3"
    if plot_shapes:
        fnames = ["mesh3/mesh_triangles.xdmf", "mesh3/domains_final.xdmf"]
        outname = ["mesh3/init_plog.png", "mesh3/final_plot.png"]
    if generate_table_opt:
        txtname = "terminal_interface_2805_.txt"   # terminal output of simulation needs to be saved to /example/FSI/txtname
        txtout = 'mesh3/table.txt'
        txtout_all = 'mesh3/to_shortened.txt'
    if generate_dp:
        foldernames = ["Init_interface", "Opt_interface"]  # folders in /example/FSI/Output/Forward generated by run_forward
        points = [[0.6, 0.2], [0.597718, 0.20417]]
    if generate_mp4:
        gifnames = ["init_fsi.gif", "opt_fsi.gif"]
    T = 30.0 #time horizon 
    deltat = 0.005 #needed, otherwise numerical issues for large time horizons
    drag = True
    factor = 1
    xrange = [0, 30]
    yrange = [-0.1, 0.1]
    move_dp = True #move displacement plot in y dir

elif option == 2:
    path_mesh = str(here) + "/" + "mesh4"
    if plot_shapes:
        fnames = ["mesh4/mesh_triangles.xdmf", "mesh4/domains_final.xdmf"] # these files are in folder /example/FSI/
        outname = ["mesh4/init_plot.png", "mesh4/final_plot.png"]
    if generate_table_opt:
        txtname = "terminal_output_example_T75_t2.txt"   # terminal output of simulation needs to be saved to /example/FSI/txtname
        txtout = 'mesh4/table.txt'
        txtout_all = 'mesh4/to_shortened.txt'
    if generate_dp:
        foldernames = ["Init", "Opt"]  # folders in /example/FSI/Output/Forward generated by run_forward
        points = [[0.3, 0.2], [0.29476, 0.184884]]
    if generate_mp4:
        gifnames = ["init_fsi.gif", "opt_fsi.gif"]
    T = 15.0 #time horizon 
    deltat = 0.01 #needed, otherwise numerical issues for large time horizons
    drag = False
    factor = 2
    xrange = [0, 15]
    yrange = [-0.0005, 0.0005]
    move_dp = False

else: 
    print("not implemented")

print('__Options set__')

if plot_shapes:
    for i in range(len(fnames)):
        print('visualize ', fnames[i])
        visualize_shape(fnames[i], outname[i], factor)

# generate latex table
from visualization.read_terminal_output import generate_table
if generate_table_opt:
    generate_table(txtname, txtout, txtout_all)

# run forward simulation on initial and optimized geometry
from visualization.run_forward_solve import run_forward

if rerun_simulation:

    only_optimized = False # set to False if initial domain was not optimized
    only_initial = False
    if only_optimized:
        initial = [False]
    elif only_initial:
        initial = [True]
    else:
        initial = [True, False]

    if False in initial:
        folder = path_mesh
        os.chdir(folder)
        os.system("cp domains_final.h5 domains_new.h5 && cp domains_final.xdmf domains_new.xdmf")
        os.system("cp facet_mesh_final.h5 facet_mesh_new.h5 && cp facet_mesh_final.xdmf facet_mesh_new.xdmf")
        os.system("cp mesh_triangles_final.h5 mesh_triangles_new.h5 && cp mesh_triangles_final.xdmf mesh_triangles_new.xdmf")

    if run_forward_opt: 
        for i in initial:
            if i:
                out_folder = foldernames[0]
                point = points[0]
            else:
                out_folder = foldernames[1]
                point = points[1]
            run_forward(i, T, deltat, path_mesh, out_folder, point, drag = drag)


# generate displacement plot
from visualization.plot_displacement import plot_displacement, colors
import numpy as np
from pathlib import Path
here = Path(__file__).parent.parent.resolve()


if generate_dp:
    names=  ["initial geometry", "optimized geometry"] 

    times_list = []
    displacement_list = []

    for i in foldernames:
        str_ = str(here) + "/FSI/Output/Forward/" + i
        times_list.append(np.loadtxt(str_ + "/times.txt"))
        dy = np.loadtxt(str_ + "/displacementy.txt")
        if move_dp:
            if i == foldernames[1]:
                dy += points[1][1] - points[0][1]
        displacement_list.append(dy)

    plot_displacement(displacement_list, times_list,
                        str(here)+"/FSI/Output/displacement_plot.pdf", colors, names, xrange, yrange)

# generate clips
from visualization.visualize_simulation import make_movie

if generate_mp4:
    only_init = False
    only_opt = False
    if only_init: 
        f_names = [foldernames[0]]
        g_names = [gifnames[0]]
    elif only_opt:
        f_names = [foldernames[1]]
        g_names = [gifnames[1]]
    else:
        f_names = foldernames
        g_names = gifnames

if generate_mp4:   
    for i in range(len(f_names)):
        make_movie(foldername=f_names[i], gifname=g_names[i])