name: testing ShapeOpt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo $(pwd)
        #docker build -t shapeopt .
    - name: Test with pytest
      run: |
        docker run -v "/var/run/docker.sock":"/var/run/docker.sock" shapeopt pytest
