name: testing ShapeOpt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -v ${{ github.repository }}:/mnt/repository/ -t shapeopt .
    - name: Test with pytest
      run: |
        docker run shapeopt pytest
